### ISSUE TITLE
404 on Chrome Store

### ISSUE THREAD

**Issue by PicoSushi** [dwyer/chromnitweet#5]
Store link on README is dead.

https://chrome.google.com/webstore/detail/ofhffnelacegjkgcbohojhebkbehikep?hl=en-US

I guess you're working ( 15681fb689c9dd37ce3b0fe03de4b2d686ba2f54 ) for fix. This app is best to tweet and I've used for long time. I wish this app to be available again!

**Comment by dwyer** [comment]
Thanks for letting me know. Google did not tell me they pulled it. All I could do is resubmit. We'll see what happens.

**Comment by dwyer** [comment]
It's back up.
