### ISSUE TITLE
403 on chrome_ex_oauth.html

### ISSUE THREAD

**Issue by PicoSushi** [dwyer/chromnitweet#6]
After installation, chromnitweet used to open `chrome_ex_oauth.html` and redirect to twitter, for authentication. But, it returns 403 before redirecting for now.

Error is below (some keys are hided):

`chrome_ex_oauth.js:299 GET https://api.twitter.com/oauth/request_token?oauth_callback=chrome-extension%3A%2F%2Fofhffnelacegjkgcbohojhebkbehikep%2Fchrome_ex_oauth.html%3Fchromeexoauthcallback%3Dtrue&oauth_consumer_key=XXXXXXXXXXXXXX&oauth_nonce=XXXX&oauth_signature=XXXXXXX&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1536565802&scope=https%3A%2F%2Fapi.twitter.com%2F1.1%2Fstatuses%2Fupdate.json&xoauth_displayname=Chromnitweet 403`

**Comment by dwyer** [comment]
Thanks for the report. I whitelisted the chrome-extension:// protocol in the Twitter Apps dashboard and it appears to be working now. Sorry for the trouble.
